<?php

namespace App\Http\Controllers;

use App\User;

class FrontController
{
    public function __invoke()
    {
        User::truncate();
        foreach (range('A', 'Z') as $char) {
            $ch = curl_init();
            curl_setopt($ch, CURLOPT_URL, "https://certification.pmi.org/registry.aspx");
            curl_setopt($ch, CURLOPT_POSTFIELDS,
                'dph_RegistryContent$wcountry=RUS&dph_RegistryContent$tbSearch='.$char.'&__VIEWSTATE=/wEPDwUJMTE5MTEyOTU2D2QWAgIDD2QWAgIDDxQrAAMPBYIBQztDOlBNSS5XZWIuRnJhbWV3b3JrLkR5bmFtaWNQbGFjZWhvbGRlciwgUE1JLldlYiwgVmVyc2lvbj0yLjAuNjg0OS4yNDA4NiwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1udWxsO0NvbnRlbnRQbGFjZWhvbGRlchYBDwVEQztVQzpBU1AucmVnaXN0cnlfcmVnaXN0cnljb250ZW50X2FzY3g6L1JlZ2lzdHJ5O2RwaF9SZWdpc3RyeUNvbnRlbnQWAGRkFgJmD2QWAmYPZBYGAgEPDxYCHgRUZXh0BQIgYWRkAgcPEGQPFvgBZgIBAgICAwIEAgUCBgIHAggCCQIKAgsCDAINAg4CDwIQAhECEgITAhQCFQIWAhcCGAIZAhoCGwIcAh0CHgIfAiACIQIiAiMCJAIlAiYCJwIoAikCKgIrAiwCLQIuAi8CMAIxAjICMwI0AjUCNgI3AjgCOQI6AjsCPAI9Aj4CPwJAAkECQgJDAkQCRQJGAkcCSAJJAkoCSwJMAk0CTgJPAlACUQJSAlMCVAJVAlYCVwJYAlkCWgJbAlwCXQJeAl8CYAJhAmICYwJkAmUCZgJnAmgCaQJqAmsCbAJtAm4CbwJwAnECcgJzAnQCdQJ2AncCeAJ5AnoCewJ8An0CfgJ/AoABAoEBAoIBAoMBAoQBAoUBAoYBAocBAogBAokBAooBAosBAowBAo0BAo4BAo8BApABApEBApIBApMBApQBApUBApYBApcBApgBApkBApoBApsBApwBAp0BAp4BAp8BAqABAqEBAqIBAqMBAqQBAqUBAqYBAqcBAqgBAqkBAqoBAqsBAqwBAq0BAq4BAq8BArABArEBArIBArMBArQBArUBArYBArcBArgBArkBAroBArsBArwBAr0BAr4BAr8BAsABAsEBAsIBAsMBAsQBAsUBAsYBAscBAsgBAskBAsoBAssBAswBAs0BAs4BAs8BAtABAtEBAtIBAtMBAtQBAtUBAtYBAtcBAtgBAtkBAtoBAtsBAtwBAt0BAt4BAt8BAuABAuEBAuIBAuMBAuQBAuUBAuYBAucBAugBAukBAuoBAusBAuwBAu0BAu4BAu8BAvABAvEBAvIBAvMBAvQBAvUBAvYBAvcBFvgBEAUQU2VsZWN0IGEgQ291bnRyeQUBMGcQBQtBZmdoYW5pc3RhbgUDQUZHZxAFDsOFbGFuZCBJc2xhbmRzBQNBTEFnEAUHQWxiYW5pYQUDQUxCZxAFB0FsZ2VyaWEFA0RaQWcQBQ5BbWVyaWNhbiBTYW1vYQUDQVNNZxAFB0FuZG9ycmEFA0FORGcQBQZBbmdvbGEFA0FHT2cQBQhBbmd1aWxsYQUDQUlBZxAFCkFudGFyY3RpY2EFA0FUQWcQBRNBbnRpZ3VhIGFuZCBCYXJidWRhBQNBVEdnEAUJQXJnZW50aW5hBQNBUkdnEAUHQXJtZW5pYQUDQVJNZxAFBUFydWJhBQNBQldnEAUJQXVzdHJhbGlhBQNBVVNnEAUHQXVzdHJpYQUDQVVUZxAFCkF6ZXJiYWlqYW4FA0FaRWcQBQdCYWhhbWFzBQNCSFNnEAUHQmFocmFpbgUDQkhSZxAFCkJhbmdsYWRlc2gFA0JHRGcQBQhCYXJiYWRvcwUDQlJCZxAFB0JlbGFydXMFA0JMUmcQBQdCZWxnaXVtBQNCRUxnEAUGQmVsaXplBQNCTFpnEAUFQmVuaW4FA0JFTmcQBQdCZXJtdWRhBQNCTVVnEAUGQmh1dGFuBQNCVE5nEAUHQm9saXZpYQUDQk9MZxAFIEJvbmFpcmUsIFNpbnQgRXVzdGF0aXVzIGFuZCBTYWJhBQNCRVNnEAUWQm9zbmlhIGFuZCBIZXJ6ZWdvdmluYQUDQklIZxAFCEJvdHN3YW5hBQNCV0FnEAUNQm91dmV0IElzbGFuZAUDQlZUZxAFBkJyYXppbAUDQlJBZxAFHkJyaXRpc2ggSW5kaWFuIE9jZWFuIFRlcnJpdG9yeQUDSU9UZxAFFkJyaXRpc2ggVmlyZ2luIElzbGFuZHMFA1ZHQmcQBRFCcnVuZWkgRGFydXNzYWxhbQUDQlJOZxAFCEJ1bGdhcmlhBQNCR1JnEAUMQnVya2luYSBGYXNvBQNCRkFnEAUHQnVydW5kaQUDQkRJZxAFCENhbWJvZGlhBQNLSE1nEAUIQ2FtZXJvb24FA0NNUmcQBQZDYW5hZGEFA0NBTmcQBQpDYXBlIFZlcmRlBQNDUFZnEAUOQ2F5bWFuIElzbGFuZHMFA0NZTWcQBRhDZW50cmFsIEFmcmljYW4gUmVwdWJsaWMFA0NBRmcQBQRDaGFkBQNUQ0RnEAUFQ2hpbGUFA0NITGcQBQ9DaGluYSwgbWFpbmxhbmQFA0NITmcQBRBDaHJpc3RtYXMgSXNsYW5kBQNDWFJnEAUXQ29jb3MgKEtlZWxpbmcpIElzbGFuZHMFA0NDS2cQBQhDb2xvbWJpYQUDQ09MZxAFB0NvbW9yb3MFA0NPTWcQBRBDb25nbywgRGVtLiBSZXAuBQNDT0RnEAULQ29uZ28sIFJlcC4FA0NPR2cQBQxDb29rIElzbGFuZHMFA0NPS2cQBQpDb3N0YSBSaWNhBQNDUklnEAUOQ8O0dGUgZCdJdm9pcmUFA0NJVmcQBQdDcm9hdGlhBQNIUlZnEAUEQ3ViYQUDQ1VCZxAFCEN1cmHDp2FvBQNDVVdnEAUGQ3lwcnVzBQNDWVBnEAUOQ3plY2ggUmVwdWJsaWMFA0NaRWcQBQdEZW5tYXJrBQNETktnEAUIRGppYm91dGkFA0RKSWcQBQhEb21pbmljYQUDRE1BZxAFEkRvbWluaWNhbiBSZXB1YmxpYwUDRE9NZxAFB0VjdWFkb3IFA0VDVWcQBQVFZ3lwdAUDRUdZZxAFC0VsIFNhbHZhZG9yBQNTTFZnEAURRXF1YXRvcmlhbCBHdWluZWEFA0dOUWcQBQdFcml0cmVhBQNFUklnEAUHRXN0b25pYQUDRVNUZxAFCEV0aGlvcGlhBQNFVEhnEAUhRmFsa2xhbmQgSXNsYW5kcyAoSXNsYXMgTWFsdmluYXMpBQNGTEtnEAUNRmFyb2UgSXNsYW5kcwUDRlJPZxAFHkZlZGVyYXRlZCBTdGF0ZXMgb2YgTWljcm9uZXNpYQUDRlNNZxAFBEZpamkFA0ZKSWcQBQdGaW5sYW5kBQNGSU5nEAUGRnJhbmNlBQNGUkFnEAUNRnJlbmNoIEd1aWFuYQUDR1VGZxAFEEZyZW5jaCBQb2x5bmVzaWEFA1BZRmcQBRtGcmVuY2ggU291dGhlcm4gVGVycml0b3JpZXMFA0FURmcQBQVHYWJvbgUDR0FCZxAFBkdhbWJpYQUDR01CZxAFB0dlb3JnaWEFA0dFT2cQBQdHZXJtYW55BQNERVVnEAUFR2hhbmEFA0dIQWcQBQlHaWJyYWx0YXIFA0dJQmcQBQZHcmVlY2UFA0dSQ2cQBQlHcmVlbmxhbmQFA0dSTGcQBQdHcmVuYWRhBQNHUkRnEAUKR3VhZGVsb3VwZQUDR0xQZxAFBEd1YW0FA0dVTWcQBQlHdWF0ZW1hbGEFA0dUTWcQBQZHdWluZWEFA0dJTmcQBQ1HdWluZWEtQmlzc2F1BQNHTkJnEAUGR3V5YW5hBQNHVVlnEAUFSGFpdGkFA0hUSWcQBSFIZWFyZCBJc2xhbmQgYW5kIE1jRG9uYWxkIElzbGFuZHMFA0hNRGcQBQhIb25kdXJhcwUDSE5EZxAFCUhvbmcgS29uZwUDSEtHZxAFB0h1bmdhcnkFA0hVTmcQBQdJY2VsYW5kBQNJU0xnEAUFSW5kaWEFA0lORGcQBQlJbmRvbmVzaWEFA0lETmcQBRlJcmFuLCBJc2xhbWljIFJlcHVibGljIG9mBQNJUk5nEAUESXJhcQUDSVJRZxAFB0lyZWxhbmQFA0lSTGcQBQZJc3JhZWwFA0lTUmcQBQVJdGFseQUDSVRBZxAFB0phbWFpY2EFA0pBTWcQBQVKYXBhbgUDSlBOZxAFBkpvcmRhbgUDSk9SZxAFCkthemFraHN0YW4FA0tBWmcQBQVLZW55YQUDS0VOZxAFCEtpcmliYXRpBQNLSVJnEAUGS3V3YWl0BQNLV1RnEAUKS3lyZ3l6c3RhbgUDS0daZxAFBExhb3MFA0xBT2cQBQZMYXR2aWEFA0xWQWcQBQdMZWJhbm9uBQNMQk5nEAUHTGVzb3RobwUDTFNPZxAFB0xpYmVyaWEFA0xCUmcQBQVMaWJ5YQUDTEJZZxAFDUxpZWNodGVuc3RlaW4FA0xJRWcQBQlMaXRodWFuaWEFA0xUVWcQBQpMdXhlbWJvdXJnBQNMVVhnEAUFTWFjYW8FA01BQ2cQBSpNYWNlZG9uaWEsIFRoZSBGb3JtZXIgWXVnb3NsYXYgUmVwdWJsaWMgb2YFA01LRGcQBQpNYWRhZ2FzY2FyBQNNREdnEAUGTWFsYXdpBQNNV0lnEAUITWFsYXlzaWEFA01ZU2cQBQhNYWxkaXZlcwUDTURWZxAFBE1hbGkFA01MSWcQBQVNYWx0YQUDTUxUZxAFEE1hcnNoYWxsIElzbGFuZHMFA01ITGcQBQpNYXJ0aW5pcXVlBQNNVFFnEAUKTWF1cml0YW5pYQUDTVJUZxAFCU1hdXJpdGl1cwUDTVVTZxAFB01heW90dGUFA01ZVGcQBQZNZXhpY28FA01FWGcQBRRNb2xkb3ZhLCBSZXB1YmxpYyBvZgUDTURBZxAFBk1vbmFjbwUDTUNPZxAFCE1vbmdvbGlhBQNNTkdnEAUKTW9udGVuZWdybwUDTU5FZxAFCk1vbnRzZXJyYXQFA01TUmcQBQdNb3JvY2NvBQNNQVJnEAUKTW96YW1iaXF1ZQUDTU9aZxAFB015YW5tYXIFA01NUmcQBQdOYW1pYmlhBQNOQU1nEAUFTmF1cnUFA05SVWcQBQVOZXBhbAUDTlBMZxAFC05ldGhlcmxhbmRzBQNOTERnEAUUTmV0aGVybGFuZHMgQW50aWxsZXMFA0FOVGcQBQ1OZXcgQ2FsZWRvbmlhBQNOQ0xnEAULTmV3IFplYWxhbmQFA05aTGcQBQlOaWNhcmFndWEFA05JQ2cQBQVOaWdlcgUDTkVSZxAFB05pZ2VyaWEFA05HQWcQBQROaXVlBQNOSVVnEAUOTm9yZm9sayBJc2xhbmQFA05GS2cQBQtOb3J0aCBLb3JlYQUDUFJLZxAFGE5vcnRoZXJuIE1hcmlhbmEgSXNsYW5kcwUDTU5QZxAFBk5vcndheQUDTk9SZxAFBE9tYW4FA09NTmcQBQhQYWtpc3RhbgUDUEFLZxAFBVBhbGF1BQNQTFdnEAUTUGFsZXN0aW5lLCBTdGF0ZSBvZgUDUFNFZxAFBlBhbmFtYQUDUEFOZxAFEFBhcHVhIE5ldyBHdWluZWEFA1BOR2cQBQhQYXJhZ3VheQUDUFJZZxAFBFBlcnUFA1BFUmcQBQtQaGlsaXBwaW5lcwUDUEhMZxAFCFBpdGNhaXJuBQNQQ05nEAUGUG9sYW5kBQNQT0xnEAUIUG9ydHVnYWwFA1BSVGcQBQtQdWVydG8gUmljbwUDUFJJZxAFBVFhdGFyBQNRQVRnEAUIUsOpdW5pb24FA1JFVWcQBQdSb21hbmlhBQNST1VnEAUSUnVzc2lhbiBGZWRlcmF0aW9uBQNSVVNnEAUGUndhbmRhBQNSV0FnEAURU2FpbnQgQmFydGjDqWxlbXkFA0JMTWcQBQxTYWludCBIZWxlbmEFA1NITmcQBRVTYWludCBLaXR0cyBhbmQgTmV2aXMFA0tOQWcQBQtTYWludCBMdWNpYQUDTENBZxAFGlNhaW50IE1hcnRpbiAoRnJlbmNoIHBhcnQpBQNNQUZnEAUgU2FpbnQgVmluY2VudCBhbmQgdGhlIEdyZW5hZGluZXMFA1ZDVGcQBRlTYWludC1QaWVycmUgYW5kIE1pcXVlbG9uBQNTUE1nEAUFU2Ftb2EFA1dTTWcQBQpTYW4gTWFyaW5vBQNTTVJnEAUYU8OjbyBUb23DqSBhbmQgUHLDrW5jaXBlBQNTVFBnEAUMU2F1ZGkgQXJhYmlhBQNTQVVnEAUHU2VuZWdhbAUDU0VOZxAFBlNlcmJpYQUDU1JCZxAFClNleWNoZWxsZXMFA1NZQ2cQBQxTaWVycmEgTGVvbmUFA1NMRWcQBQlTaW5nYXBvcmUFA1NHUGcQBRlTaW50IE1hYXJ0ZW4gKER1dGNoIHBhcnQpBQNTWE1nEAUIU2xvdmFraWEFA1NWS2cQBQhTbG92ZW5pYQUDU1ZOZxAFD1NvbG9tb24gSXNsYW5kcwUDU0xCZxAFB1NvbWFsaWEFA1NPTWcQBQxTb3V0aCBBZnJpY2EFA1pBRmcQBSxTb3V0aCBHZW9yZ2lhIGFuZCB0aGUgU291dGggU2FuZHdpY2ggSXNsYW5kcwUDU0dTZxAFC1NvdXRoIEtvcmVhBQNLT1JnEAULU291dGggU3VkYW4FA1NTRGcQBQVTcGFpbgUDRVNQZxAFCVNyaSBMYW5rYQUDTEtBZxAFBVN1ZGFuBQNTRE5nEAUIU3VyaW5hbWUFA1NVUmcQBRZTdmFsYmFyZCBhbmQgSmFuIE1heWVuBQNTSk1nEAUJU3dhemlsYW5kBQNTV1pnEAUGU3dlZGVuBQNTV0VnEAULU3dpdHplcmxhbmQFA0NIRWcQBRRTeXJpYW4gQXJhYiBSZXB1YmxpYwUDU1lSZxAFGlRhaXdhbiAoUmVwdWJsaWMgb2YgQ2hpbmEpBQNUV05nEAUKVGFqaWtpc3RhbgUDVEpLZxAFHFRhbnphbmlhLCBVbml0ZWQgUmVwdWJsaWMgT2YFA1RaQWcQBQhUaGFpbGFuZAUDVEhBZxAFC1RpbW9yLUxlc3RlBQNUTFNnEAUEVG9nbwUDVEdPZxAFB1Rva2VsYXUFA1RLTGcQBQVUb25nYQUDVE9OZxAFE1RyaW5pZGFkIGFuZCBUb2JhZ28FA1RUT2cQBQdUdW5pc2lhBQNUVU5nEAUGVHVya2V5BQNUVVJnEAUMVHVya21lbmlzdGFuBQNUS01nEAUYVHVya3MgYW5kIENhaWNvcyBJc2xhbmRzBQNUQ0FnEAUGVHV2YWx1BQNUVVZnEAUTVS5TLiBWaXJnaW4gSXNsYW5kcwUDVklSZxAFBlVnYW5kYQUDVUdBZxAFB1VrcmFpbmUFA1VLUmcQBRRVbml0ZWQgQXJhYiBFbWlyYXRlcwUDQVJFZxAFDlVuaXRlZCBLaW5nZG9tBQNHQlJnEAUNVW5pdGVkIFN0YXRlcwUDVVNBZxAFJFVuaXRlZCBTdGF0ZXMgTWlub3IgT3V0bHlpbmcgSXNsYW5kcwUDVU1JZxAFB1VydWd1YXkFA1VSWWcQBQpVemJla2lzdGFuBQNVWkJnEAUHVmFudWF0dQUDVlVUZxAFB1ZhdGljYW4FA1ZBVGcQBQlWZW5lenVlbGEFA1ZFTmcQBQhWaWV0IE5hbQUDVk5NZxAFEVdhbGxpcyBhbmQgRnV0dW5hBQNXTEZnEAUOV2VzdGVybiBTYWhhcmEFA0VTSGcQBQVZZW1lbgUDWUVNZxAFBlphbWJpYQUDWk1CZxAFCFppbWJhYndlBQNaV0VnFgFmZAIJDxBkDxYJZgIBAgICAwIEAgUCBgIHAggWCRAFA0FsbAUBMGcQBQNQTVAFATFnEAUEQ0FQTQUBMmcQBQRQZ01QBQEzZxAFB1BNSS1STVAFATRnEAUGUE1JLVNQBQE1ZxAFB1BNSS1BQ1AFATZnEAUEUGZNUAUBN2cQBQdQTUktUEJBBQE4ZxYBZmQYAQUeX19Db250cm9sc1JlcXVpcmVQb3N0QmFja0tleV9fFgIFHEhlYWRlcjEkUE1JTG9naW5TdGF0dXMkY3RsMDEFHEhlYWRlcjEkUE1JTG9naW5TdGF0dXMkY3RsMDMFdcDVG9qzmyjtq0Qp4E0qZ56PaA==');
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($ch, CURLOPT_POST, true);
            $output = curl_exec($ch);
            curl_close($ch);
            $dom = new \DOMDocument();
            libxml_use_internal_errors(true);
            $dom->loadHTML($output);
            libxml_clear_errors();
            $xpath = new \DOMXPath($dom);
            $data = $res = [];
            $table_rows = $xpath->query('//table/tr');
            foreach ($table_rows as $row => $tr) {
                $index = 0;
                for($i = 0; $i < count($tr->childNodes); $i+=2) {
                    if($row  == 0) {
                        $keys[] =  preg_replace('~[\r\n]+~', '', trim(strtolower($tr->childNodes[$i]->nodeValue)));
                    }
                    else {
                        if (empty(preg_replace('~[\r\n]+~', '', trim($tr->childNodes[$i]->nodeValue)))) {
                            $data[$row][] = $data[$row-1][$index];
                            $index ++;
                        }
                        else {
                            $data[$row][] = preg_replace('~[\r\n]+~', '', trim($tr->childNodes[$i]->nodeValue));
                        }
                    }
                    if (!empty($temp)) {
                        if(count($keys) != count($temp)){
                            $keys = array_slice($keys, 0, count($temp));
                        }
                        $res[] = array_combine($keys,$temp);
                        $temp = [];
                    }
                }
                if (!empty($data[$row])) $temp = $data[$row];
            }
            User::insert($res);
        }
    }
}
